lappend ::auto_path\
    $TKSERVER/tk/lib/prototype\
    \
    $TKSERVER/tk/lib/common\
    $TKSERVER/tk/lib/components/tk\
    $TKSERVER/tk/lib/components/tb\
    $TKSERVER/tk/lib/components/tk\
    $TKSERVER/tk/lib/components/jq\
    $TKSERVER/tk/lib/components/ch\
    $TKSERVER/tk/lib/components/mtk\
    $TKSERVER/tk/lib/components/polymer\
    $TKSERVER/tk/lib/components/mtk/src\
    $TKSERVER/tk/lib/components/pl\
    $TKSERVER/tk/lib/components/d3\
    $TKSERVER/tk/lib/components/ang\
    $TKSERVER/tk/lib/components/jqw\
    $TKSERVER/tk/lib/components/wc\
    $TKSERVER/tk/lib/components/fm\
    $TKSERVER/tk/lib/components/tmp\
    \
    $TKSERVER/tk/lib/components/w3c/tcl\
    $TKSERVER/tk/lib/components/w3c/mtk\
    \
    $TKSERVER/tk/lib/modules/videos\
    $TKSERVER/tk/lib/modules/email\
    $TKSERVER/tk/lib/modules/users\
    $TKSERVER/tk/lib/modules/post\
    $TKSERVER/tk/lib/modules/play\
    $TKSERVER/tk/lib/modules/db/sqlite/viewer\
    \
    $TKSERVER/tk/lib/forms\
    \
    /tmp

